### ISSUE TITLE
Exception thrown on second run of serve task in REPL with same port

### ISSUE THREAD

**Issue by cigitia** [pandeiro/boot-http#25]
A `java.net.BindException: Address already in use` exception is thrown on the second run of the `serve` task when using the same port as before. For instance:
1. Boot the REPL with `boot repl` (assuming that `build.boot` uses boot-http)
2. Run `(boot (serve))` (displays a message saying Jetty has started on port 3000, then ends the Boot pipeline, without displaying any messages saying that Jetty has stopped).
3. Run `(boot (serve))` again. The error at https://gist.github.com/cigitia/5e7fb38cc44571dd6921 appears.

**Comment by pandeiro** [comment]
@cigitia I'm really not sure why this is; thanks for bringing it to my attention. The expected behavior would be that `(boot (serve))` exits immediately and the server it creates is stopped, complete with output to that effect (see [here](https://github.com/pandeiro/boot-http/blob/master/src/pandeiro/boot_http.clj#L70-L82)). Very odd.

cc @micha Any ideas?

**Comment by agzam** [comment]
it would be nice to have a way to "kill" jetty/http-kit server without having to restart the repl.
