### ISSUE TITLE
0.4.2 serves index.html from dependency

### ISSUE THREAD

**Issue by sparkofreason** [pandeiro/boot-http#9]
We have internal libraries with their own index.html files for development testing. These wind up in the jar due to how boot treats files marked as assets. When I upgrade to 0.4.2 from 0.4.1, boot-http serves the index.html from one of the included libraries, not the main project. Going back to 0.4.1 restores the original behavior.

**Comment by pandeiro** [comment]
Thanks for the heads-up, Dave.

This was added [here](https://github.com/pandeiro/boot-http/commit/806a58c9592bc10ba3df0f24b0f67fef742acf60#diff-7c33f1922c30e7cf558e63c0e8924992R62) so that the resources handler acted similarly to the directory handler and served an `index.html` if one existed. At the time I thought it was a good idea but maybe we need to rethink it. I think that might be a little too magical. Pinging @Deraen.

Perhaps a workaround might be to specify the :resource-root so that no such index file is found, though that might break or necessitate other changes to your workflow.

Would like to get input on this before taking action.

**Comment by Deraen** [comment]
So you depend on .jars which have index.html on their root?

It's not boot specific that (io/resource "index.html") might return file from one of your dependencies. Thats how classpath works. In leiningen it happens that files in your local project are found first.

In general it's good idea to not have files in jars which might interfere with other projects.

In internal libraries you can use sift to filter fileset before creating the jar:
```
(sift :exclude #{#"^index.html"})
```

Alternately you could remove the asset-path containing index.html before the build task:
```
(set-env! (update-in (get-env) :asset-paths disj "resources"))
```

**Comment by pandeiro** [comment]
@sparkofreason I think @Deraen is right; we can't fix the problem of the same file (`index.html`) existing in the root of the resource path via different jars. Besides the fix above to deal with the root problem, you could also paper it over by writing your own handler and using `serve -H myapp/handler`, then you deal with resources and whatnot however you wish.

**Comment by pandeiro** [comment]
A pretty extreme solution would be to add a flag (:resource-index?) that is enabled by default but can be disabled in cases where a stray `index.html` has shown up at / on the classpath. Does anyone think that is necessary?

**Comment by sparkofreason** [comment]
For my case, at least, leaving out the index.html in the jar is preferable. It's only there for interactive testing, and I didn't really want it in there in the first place, just wasn't aware there was a way to leave it out. Let me give sift a try.

**Comment by sparkofreason** [comment]
Was able to exclude using both suggestions @Deraen. Thanks for your help, closing.
